In [6]:
import pandas as pd
import numpy as np

df = pd.read_csv('student_marksheet.csv')
df

,Name,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,28
0,lli,1,1,1,1,1,1,1,1,1,...,1,1,1,0,0,0,0,0,0,0
1,tal,1,0,0,1,1,1,0,1,1,...,1,1,0,0,0,0,0,0,0,0
2,ira,1,1,1,1,1,1,1,1,1,...,1,1,0,0,0,0,1,0,0,0
3,ana,1,0,1,1,0,1,1,1,0,...,1,1,0,0,0,0,0,0,0,0
4,wat,1,1,1,1,1,1,0,1,1,...,1,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,cob,1,1,1,1,1,1,1,1,1,...,1,1,1,1,0,0,1,0,0,0
91,ash,1,1,1,1,1,1,1,1,1,...,1,1,1,1,0,0,1,0,0,1
92,ddy,1,0,1,1,1,1,1,1,1,...,0,1,0,0,0,0,1,0,0,1
93,aju,1,1,1,1,1,1,1,1,1,...,1,1,1,0,0,0,1,1,0,0
94,ppa,1,1,1,1,0,1,1,1,1,...,1,1,1,0,0,0,1,1,1,1

In [7]:
df.describe()

,1,2,3,4,5,6,7,8,9,10,...,19,20,21,22,23,24,25,26,27,28
count,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,...,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000
mean,0.905263,0.736842,0.968421,0.957895,0.821053,0.957895,0.842105,0.957895,0.936842,0.926316,...,0.768421,0.968421,0.484211,0.189474,0.031579,0.147368,0.757895,0.221053,0.157895,0.315789
std,0.294405,0.442683,0.175804,0.201895,0.385342,0.201895,0.366577,0.201895,0.244537,0.262642,...,0.424079,0.175804,0.502402,0.393963,0.175804,0.356353,0.430630,0.417157,0.366577,0.467295
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
50%,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
75%,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [11]:


# Calculate total score per person
df["total_score"] = df.loc[:, "1":"27"].sum(axis=1)

# Calculate percentage score
df["percentage"] = df["total_score"] / 28 * 100

# Item analysis: how many people got each question correct
item_analysis = df.loc[:, "1":"27"].sum(axis=0)

print(item_analysis)

1     86
2     70
3     92
4     91
5     78
6     91
7     80
8     91
9     89
10    88
11    68
12    80
13    61
14    68
15    65
16    61
17    91
18    73
19    73
20    92
21    46
22    18
23     3
24    14
25    72
26    21
27    15
dtype: int64

In [13]:


# Calculate total score for each student
df["total_score"] = df.loc[:, "1":"27"].sum(axis=1)

# Preview results
print(df[["Name", "total_score"]])

   Name  total_score
0   lli           21
1   tal           16
2   ira           18
3   ana           16
4   wat           19
..  ...          ...
90  cob           21
91  ash           22
92  ddy           15
93  aju           19
94  ppa           23

[95 rows x 2 columns]

In [14]:
df["percentage"] = (df["total_score"] / 28) * 100

print(df[["Name", "total_score", "percentage"]])

   Name  total_score  percentage
0   lli           21   75.000000
1   tal           16   57.142857
2   ira           18   64.285714
3   ana           16   57.142857
4   wat           19   67.857143
..  ...          ...         ...
90  cob           21   75.000000
91  ash           22   78.571429
92  ddy           15   53.571429
93  aju           19   67.857143
94  ppa           23   82.142857

[95 rows x 3 columns]

In [15]:
# Classify students based on percentage 
def classify(pct):
    if pct >= 60: 
        return "Advanced"
    elif pct >= 50: 
        return "Upper Intermediate"
    elif pct >= 40: 
        return "Intermediate"
    else: 
        return "Beginner" 
df["level"] = df["percentage"].apply(classify) 
# Preview results
print(df[["Name", "total_score", "percentage", "level"]])

   Name  total_score  percentage               level
0   lli           21   75.000000            Advanced
1   tal           16   57.142857  Upper Intermediate
2   ira           18   64.285714            Advanced
3   ana           16   57.142857  Upper Intermediate
4   wat           19   67.857143            Advanced
..  ...          ...         ...                 ...
90  cob           21   75.000000            Advanced
91  ash           22   78.571429            Advanced
92  ddy           15   53.571429  Upper Intermediate
93  aju           19   67.857143            Advanced
94  ppa           23   82.142857            Advanced

[95 rows x 4 columns]

In [16]:
df.to_csv("student_scores.csv", index=False)

print("Excel file 'student_scores.xlsx' has been created successfully!")

Excel file 'student_scores.xlsx' has been created successfully!

In [18]:
!pip install openpyxl
df.to_excel("student_scores.xlsx", index=False)

Requirement already satisfied: openpyxl in c:\program files\python312\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\program files\python312\lib\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [19]:
level_counts = df["level"].value_counts() 
print(level_counts)

level
Advanced              63
Upper Intermediate    23
Intermediate           7
Beginner               2
Name: count, dtype: int64